export const IMAGE_WIDTH = 750
export const IMAGE_HEIGHT = 500

export const EXPANDED_IMAGE_WIDTH = 900
export const EXPANDED_IMAGE_HEIGHT = 600

export const IMAGE_GUTTER = 20
export const IMAGE_MARGIN = (EXPANDED_IMAGE_WIDTH - IMAGE_WIDTH) / 2 + IMAGE_GUTTER
